services:
  db:
    image: postgres:latest
    container_name: predictions_db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=tega
      - POSTGRES_PASSWORD=postgres
    restart: always

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: